imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ProyectoEmpBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] } 
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
 #   default_locale:  "%locale%"
    default_locale:  es
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'TetranzSelect2EntityBundle:Form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
#ElasticSearch
fos_elastica:
   clients:
         default: {host:localhost, port:9200}
   indexes:
       search:
           finder: ~
           client: default
           types:
               ofertas:
                   mappings:
                       titulopuesto: ~
                       provinciapuesto: ~
                       estado: ~
                   persistence:
                       driver: orm
                       model: ProyectoEmpBundle\Entity\Eofertas
                       finder: ~    
                       provider: ~
                       listener: ~
#fos_elastica:
#    clients:
#        default: {host:localhost, port:9200}
#        indexes:
#            app:
#                types:
#                    user:
#                        mappings:
#                            titulopuesto: ~
#                            provinciapuesto: ~
#                        persistence:
#                            driver: orm
#                            # the driver can be orm, mongodb, phpcr or propel
#                            # listener and finder are nort supported by 
#                            # propel and should be removed
#                            model: ProyectoEmpBundle\Entity\Eofertas
#                            provider: ~
#                            listener: ~
#                            finder: ~

# app/config/config.yml
#assetic:
#    debug:                '%kernel.debug%'
#    use_controller:
#        enabled:              '%kernel.debug%'
#        profiler:             false
#    read_from:            '%assetic.read_from%'
#    write_to:             '%kernel.root_dir%/../web'
#    java:                 /usr/bin/java
#    node:                 /usr/bin/node
#    ruby:                 /usr/bin/ruby
#    sass:                 /usr/bin/sass
#    # An key-value pair of any number of named elements
#    variables:
#        some_name:                 []
#    bundles:
#
#        # Defaults (all currently registered bundles):
#        - FrameworkBundle
#        - SecurityBundle
#        - TwigBundle
#        - MonologBundle
#        - SwiftmailerBundle
#        - DoctrineBundle
#        - AsseticBundle
#        - ...
#    assets:
#        # An array of named assets (e.g. some_asset, some_other_asset)
#        some_asset:
#            inputs:               []
#            filters:              []
#            options:
#                # A key-value array of options and values
#                some_option_name: []
#    filters:
#
#        # An array of named filters (e.g. some_filter, some_other_filter)
#        some_filter:                 []
#    workers:
#        # see https://github.com/symfony/AsseticBundle/pull/119
#        # Cache can also be busted via the framework.assets.version
#        # setting - see the "framework" configuration section
#        cache_busting:
#            enabled:              false
#    twig:
#        functions:
#            # An array of named functions (e.g. some_function, some_other_function)
#            some_function:                 []
#tetranz_select2_entity:
#    minimum_input_length: 2
#    page_limit: 8
#    allow_clear: true
#    delay: 500
#    language: fr
#    cache: false
#    cache_timeout: 0
#    scroll: true