# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:           
      ProyectoEmpBundle\Entity\Usuarios: 
            algorithm: sha512
            encode_as_base64: false
            iterations: 4
            
      ProyectoEmpBundle\Entity\Eusuarios: 
            algorithm: sha512
            encode_as_base64: false
            iterations: 4
    
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [our_db_provider, comp_db_provider] 
        our_db_provider:
            entity: 
                class: ProyectoEmpBundle:Usuarios
                property: email        
                
        comp_db_provider:  
            entity: 
                class: ProyectoEmpBundle:Eusuarios
                property: email   
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        complogin:
            anonymous: ~  
            provider: chain_provider
            form_login:  
                 login_path:      /complogin
                 check_path:      /login_check
                 
            logout:
                path: /logout
                target: /inicio    
                
#            provider: our_db_provider
#            form_login: 
#                 login_path:   /mylogin
#                 check_path:   /login_check
        
#        main:
#        mylogin:
#            anonymous: ~
#            provider: our_db_provider
#            form_login: 
#                 login_path:   /mylogin
#                 check_path:   /login_check
#
#            logout:
#                path:   /logout
#                target: /mylogin 
                
        
                
       

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

       